# Tomcat
server:
    name: iBase4J-Biz-Web
    port: 8090
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    compression:
        enabled: true
        min-response-siz: 1024
        mime-types: application/json,application/xml,application/octet-stream,text/html,text/xml,text/plain,text/css,text/javascript
# mysql
spring:
    # 环境 dev|test|prod
    profiles:
        active: ${spring.profiles.active}
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
    http:
        #上传文件大小设置
        multipart:
            maxFileSize: 10Mb
            maxRequestSize: 50Mb